version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "globals-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ka3t5aj9nz8l"
s3_prefix = "globals-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
